/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;


import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import usuario.home1;

/**
 *
 * @author ADMIN
 */
public class login extends javax.swing.JFrame {
    int xMause,yMause;
    public login() {
        initComponents();
       home1 pasar = new  home1();

    }
    
    
    @Override
public Image getIconImage(){
    Image ver = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Iconos/productos.png"));
return ver;
}
    
    
    
     public static final String url="jdbc:mysql://localhost:3306/muebles";
public static final String usuario="root";
public static final String clave="";
    PreparedStatement pt;
    ResultSet rs;
    public static Connection getConnection(){
    Connection cone=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cone=DriverManager.getConnection(url,usuario,clave);
            System.out.println("conecion exitosa");
            
         } catch (ClassNotFoundException | SQLException e) {
            System.err.println(" error en la conexion "+e);
            JOptionPane.showMessageDialog(null, "error en la conexion");
        }
    return cone;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pass = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        enter = new javax.swing.JPanel();
        ente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        sali = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        infor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MonteroSoft/Login");
        setIconImage(getIconImage());
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagenn_1_1_1.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 0, 380, 540));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setText("INICIAR SESION");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("USUARIO");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("ingrese su usuario");
        txtUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 300, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("CONTRASEÑA");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 282, 300, 20));

        pass.setForeground(new java.awt.Color(204, 204, 204));
        pass.setText("************");
        pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passMousePressed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passKeyTyped(evt);
            }
        });
        bg.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 300, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 300, 10));

        enter.setBackground(new java.awt.Color(0, 153, 153));
        enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ente.setText("ENTRAR");
        ente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enteMouseExited(evt);
            }
        });
        ente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout enterLayout = new javax.swing.GroupLayout(enter);
        enter.setLayout(enterLayout);
        enterLayout.setHorizontalGroup(
            enterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        enterLayout.setVerticalGroup(
            enterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ente, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bg.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 90, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        sali.setBackground(new java.awt.Color(255, 255, 255));

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("X");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout saliLayout = new javax.swing.GroupLayout(sali);
        sali.setLayout(saliLayout);
        saliLayout.setHorizontalGroup(
            saliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        saliLayout.setVerticalGroup(
            saliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 800, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 30));

        infor.setBackground(new java.awt.Color(255, 0, 0));
        infor.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        infor.setForeground(new java.awt.Color(255, 0, 51));
        infor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(infor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
xMause=evt.getX();
yMause=evt.getY();
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMause,y- yMause);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        JOptionPane.showMessageDialog(rootPane,"¡ Gracias por usar MonteroSoft !");
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        sali.setBackground(Color.red);
        salir.setBackground(Color.white);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        sali.setBackground(Color.white);
        salir.setBackground(Color.black);
    }//GEN-LAST:event_salirMouseExited

    private void enteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enteMouseEntered
       enter.setBackground(new Color(0,204,204));
    }//GEN-LAST:event_enteMouseEntered

    private void enteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enteMouseExited
       enter.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_enteMouseExited

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        if(txtUsuario.getText().equals("ingrese su usuario")){
        txtUsuario.setText("");
        txtUsuario.setForeground(Color.black);
        }
       if(String.valueOf(pass.getPassword()).isEmpty()){
           pass.setText("************");
        pass.setForeground(Color.gray);
    }
    
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMousePressed
        if(String.valueOf(pass.getPassword()).equals("************")){
         pass.setText("");
       pass.setForeground(Color.black);
        }
        if(txtUsuario.getText().isEmpty()){ 
        txtUsuario.setText("ingrese su usuario");
        txtUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passMousePressed

    private void enteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enteMouseClicked
       Connection cone=null;
      String Usuario=txtUsuario.getText();
       String Clave=pass.getText();
        String cargo = "usuario";
        PreparedStatement PT; //Recibe la sentencia Sql
    ResultSet RS; //Regresa los valores de la sentencia
    
        try {
            cone= getConnection();
            PT=cone.prepareStatement("SELECT * from usuario where nombre_usu='"+Usuario+"' AND contraseña='"+Clave+"' AND cargo='"+cargo+"'");
           
           RS=PT.executeQuery();
            if (RS.next()) {
                JOptionPane.showMessageDialog(null, "Bienvenido al perfil de usuario");
               home1 inicio = new home1 ();
               inicio.setVisible(true);
               dispose();
                home1.textousuario.setText(txtUsuario.getText());//AQUI
               
            } else {
                String usuario1=txtUsuario.getText();
       String Clave1=pass.getText();
       String cargo1 = "admin";
        try {
            cone=getConnection();
            PT=cone.prepareStatement("SELECT * from usuario where nombre_usu='"+usuario1+"' AND contraseña='"+Clave1+"' AND cargo='"+cargo1+"'");
           
           RS=PT.executeQuery();
            if (RS.next()) { //Obtiene los valores de la consulta
                JOptionPane.showMessageDialog(null, "Bienvenido al perfil de Administrador");
               inicioadmi admin = new inicioadmi();//llamamos la clase con una intacia
               admin.setVisible(true);//visualiza from de administrador
               dispose();
               
                       inicioadmi.textoadmin.setText(txtUsuario.getText());//AQUI para visualisar el nombre del usuario en from
            } else {
                JOptionPane.showMessageDialog(null, "usuario o contraseña incorrecta");
            }
        } catch (SQLException | HeadlessException e) {//regresa un valor si hay un error en la conexion
            System.out.println("monterosoft.login.BtnEntrarMouseClicked()"+e);
        }
                
            }
        } catch (SQLException | HeadlessException e) {//regresa un valor si hay un error en la conexion
            System.out.println("monterosoft.login.BtnEntrarMouseClicked()"+e);
        }
       
        
      
       
        
       
       
    }//GEN-LAST:event_enteMouseClicked

    private void enteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_enteKeyReleased

    private void enteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enteKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_enteKeyPressed

    private void passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_passKeyReleased

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_passKeyPressed

    private void passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyTyped
        // TODO add your handling code here:
  
    }//GEN-LAST:event_passKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel ente;
    private javax.swing.JPanel enter;
    private javax.swing.JLabel infor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JPasswordField pass;
    private javax.swing.JPanel sali;
    private javax.swing.JLabel salir;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
